### ISSUE TITLE
Task 1 Checklist

### ISSUE THREAD

**Issue by Hughem27** [Hughem27/emergingtech#1]
- [x]  Read texts into file and stored them in a list 
- [x] Combine text to one file 
- [x] Clean text for processing
- [x] Generate a Trigram Model of the English language
- [x] Save trigram model file.
