### ISSUE TITLE
Eliza Chatbot Checklist

### ISSUE THREAD

**Issue by Hughem27** [Hughem27/emergingtech#2]
- [x] Create index page, style sheet and Eliza.js file
- [x] Create user input box
- [x] Listen for user input 
- [x] Analyze user message
- [x] Return suitable message
