### ISSUE TITLE
Task 2 Checklist

### ISSUE THREAD

**Issue by Hughem27** [Hughem27/emergingtech#3]
- [x]  Generate the next character based on the  previous two characters-
- [x] Use the counts as weights
- [x] Then choose one of the third letters of the generated trigrams
- [x] Generate 10,000 characters and let it equal to 'TH'
